import "./globals.css";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>Online Shop</title>
        <meta
          property="og:title"
          content="Generated by create next app"
          key="title"
        />
      </head>
      <body>{children}</body>
    </html>
  );
}
